### ISSUE TITLE
Too many coments

### ISSUE THREAD

**Issue by alextudose** [danvatamaniuc/SharpNewsSite#1]
I do like how you document your code. Unfortunately it is too documented and it may
make it a bit hard to cosmeticize your heavy comented code. Do not comment lines like ,,getSomething'' with //this gets Something , it's useless, code is meant to be readible not spammed by comments.

**Comment by danvatamaniuc** [comment]
Noted, will avoid excessive commenting. However, since it's a homework project, I felt compelled to literally comment every single line as an exercise to understand better what's happening.

Thanks for the feedback!
